soncoiz02/DATN-BE

src/controllers/category.js

fix: read category

---

api.yaml
src/controllers/serviceStep.js
src/index.js
src/models/serviceStep.js
src/routes/serviceStep.js

làm crud của service step với swagger , son merge zô hộ với

Feat service step

---

api.yaml
src/controllers/order.js
src/index.js
src/models/order.js
src/routes/order.js

Feat order

---

api.yaml
src/controllers/order.js
src/controllers/service.js
src/index.js
src/models/order.js
src/models/service.js
src/routes/order.js

cập nhật  thêm cái step trong bảng service , với coment swagger

feat: update model-service

---

src/controllers/service.js
src/models/service.js

feat: edit step in serivce

---

src/controllers/order.js

update serviceId crud in order

feat: update serviceId crud in order

---

src/controllers/storeMemberShip.js
src/index.js
src/models/storeMemberShip.js
src/routes/storeMemberShip.js

fix: conflic up git

---

src/controllers/auth.js
src/controllers/user.js
src/index.js
src/models/user.js
src/routes/auth.js
src/routes/user.js

khả năng lại rất nhiều conflicts rồi

Feat  api userr

---

src/controllers/storeMemberShip.js
src/controllers/usernotify.js
src/index.js
src/models/storeMemberShip.js
src/models/usernotify.js
src/routes/storeMemberShip.js
src/routes/usernotify.js

Feat  api user notify

---

src/controllers/order.js
src/controllers/storeMemberShip.js
src/index.js
src/models/storeMemberShip.js
src/routes/order.js
src/routes/storeMemberShip.js

api order lọc userId đã đăng ký dịch vụ nào theo bảng service

feat: filter-serviceorder-by-user

---

src/controllers/advancedStore.js
src/models/store.js
src/routes/store.js

Feat  api advanced store

---

src/controllers/category.js
src/controllers/service.js
src/models/category.js
src/models/service.js
src/routes/category.js
src/routes/service.js

feat: search-service

---

src/controllers/advancedStore.js
src/controllers/store.js
src/models/store.js

merge lại toi với nhe nãy làm nhầm

fix: advancedApiStore

---

src/controllers/service.js
src/routes/service.js

feat: sort by rated-avg
lọc dịch vụ theo đánh giá - avg

feat: sort by rated-avg

---

package-lock.json
package.json
src/controllers/auth.js
src/controllers/user.js
src/controllers/userRole.js
src/index.js
src/models/user.js
src/models/userRole.js
src/routes/userRole.js

Feat  role user

---

src/controllers/service.js
src/routes/service.js

Advanced order

---

src/controllers/advancedStore.js
src/controllers/service.js
src/controllers/store.js
src/controllers/storeRating.js
src/models/store.js
src/routes/store.js
src/routes/storeRating.js

Feat  api store rated

---

src/controllers/category.js
src/controllers/orderStatus.js
src/controllers/post.js
src/controllers/store.js
src/controllers/storenotify.js
src/controllers/user.js
src/controllers/userRole.js
src/controllers/usernotify.js
src/routes/userRole.js

fix: _id update controllers

---

src/controllers/service.js
src/routes/service.js

lọc dịch vụ theo cateogory + giá + đánh giá

feat: filter service by cate and price

---

src/controllers/category.js

feat: update remove category

---

src/controllers/store.js
src/routes/store.js

list ra tổng doanh thu của cửa hàng , doanh thu của từng dịch vụ

feat: revenue store

---

src/controllers/store.js

- cập nhật lại cách tính voucher
- xóa service trống ,..

Store revenue

---

src/controllers/category.js

kiểm tra tên khi thêm mới danh mục

feat: check name when creating new category

---

src/controllers/serviceRating.js
src/routes/serviceRating.js

api list 4 đánh giá có đánh giá cao nhất

Advance service rating

---

src/controllers/user.js
src/routes/user.js

- cập nhật thêm chỉ lấy những user có roleId có name là Customer

Advance user

---

src/controllers/user.js

- cập nhật thêm những dịch vụ mà user đã đặt

feat: list of services that the user subscribes
